[project]
name = "asi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "einops>=0.8.2",
    "ftfy>=6.3.1",
    "opencv-python>=4.13.0.92",
    "packaging>=25.0",
    "pillow>=11.3.0",
    "pip>=26.0.1",
    "pytorch-metric-learning>=2.9.0",
    "regex>=2025.10.23",
    "torchaudio>=2.11.0",
    "torchvision>=0.26.0",
]
